### ISSUE TITLE
Publish package to NPM after a successful test run

### ISSUE THREAD

**Issue by lazzarello** [quantstamp/qs-ui-library#13]
The `semantic-release` library uses a grammar written in the commit message to determine when to publish a new release to NPM. This process requires configuration to enable publishing via Travis-Ci. Determine the details to ensure releases are published.

**Comment by jeffscottward** [comment]
Correct. 

An EggHead.io video (3 years old) 
https://egghead.io/lessons/javascript-automating-releases-with-semantic-release

As well as the current docs
https://semantic-release.gitbook.io/semantic-release/usage/ci-configuration#automatic-setup-with-semantic-release-cli

mentions using the `semantic-release-cli` to generate the needed setup

**Comment by jeffscottward** [comment]
[UPDATE]
Didn't verify my email with NPM. Could be causing issues. Trying again.

**Comment by lazzarello** [comment]
TravisCI requires a secret environment variable named `GITHUB_TOKEN` to be set to make releases.

https://semantic-release.gitbook.io/semantic-release/usage/ci-configuration

It also requires a env var named `NPM_TOKEN` to publish to npm.

**Comment by lazzarello** [comment]
Confirmed these two env vars are set. Creating new ticket to send them into our secrets repo.

**Comment by lazzarello** [comment]
ref #14

**Comment by lazzarello** [comment]
publishing a package to NPM requires the [publish plugin](https://semantic-release.gitbook.io/semantic-release/usage/plugins#publish-plugin)

**Comment by lazzarello** [comment]
I think there's some versioning conventions that must be followed for the tagging to function

```
21:31:46] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/npm"
[21:31:46] [semantic-release] [@semantic-release/npm] › ℹ  Wrote version 1.0.0 to /home/travis/build/quantstamp/qs-ui-library/package.json
[21:31:46] [semantic-release] [@semantic-release/npm] › ℹ  Wrote version 1.0.0 to /home/travis/build/quantstamp/qs-ui-library/package-lock.json
[21:31:46] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/npm"
[21:31:46] [semantic-release] › ✖  An error occurred while running semantic-release: { Error: Command failed: git tag v1.0.0
fatal: tag 'v1.0.0' already exists
    at makeError (/home/travis/build/quantstamp/qs-ui-library/node_modules/execa/index.js:172:9)
    at Promise.all.then.arr (/home/travis/build/quantstamp/qs-ui-library/node_modules/execa/index.js:277:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 128,
  stdout: '',
  stderr: 'fatal: tag \'v1.0.0\' already exists\n',
  failed: true,
  signal: null,
  cmd: 'git tag v1.0.0',
  timedOut: false,
  killed: false }
{ Error: Command failed: git tag v1.0.0
fatal: tag 'v1.0.0' already exists
    at makeError (/home/travis/build/quantstamp/qs-ui-library/node_modules/execa/index.js:172:9)
    at Promise.all.then.arr (/home/travis/build/quantstamp/qs-ui-library/node_modules/execa/index.js:277:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 128,
  stdout: '',
  stderr: 'fatal: tag \'v1.0.0\' already exists\n',
  failed: true,
  signal: null,
  cmd: 'git tag v1.0.0',
  timedOut: false,
  killed: false }
```
